version: '3'
services:
  app-dev:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - CONN_STR=mongodb+srv://ruffle:7112812kreZ@cluster-ruffle.vplqcb5.mongodb.net/?retryWrites=true&w=majority
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ruffle
      - MONGO_INITDB_ROOT_PASSWORD=7112812kreZ
